<template>
  <div class="page-shell"><AppHeader /><main class="page-main"><div class="container profile-layout">
    <aside class="profile-card surface"><div class="large-avatar">{{ auth.user?.name?.charAt(0)||'?' }}</div><span class="role-badge">{{ auth.isInstructor?'학교 관리자':'학교 구성원' }}</span><h2>{{ auth.user?.name||'사용자' }}</h2><p>{{ auth.user?.email }}</p><div class="profile-divider"></div><small>GearHub의 금액은 도입 예산 검토용이며 실제 결제가 발생하지 않습니다.</small></aside>
    <section><div class="page-heading compact-heading"><div><span class="eyebrow">MY GEARHUB</span><h1 class="page-title">나의 캠퍼스 허브</h1><p class="page-subtitle">소속 그룹과 전체 요청 현황을 확인하세요.</p></div></div>
      <div v-if="loading" class="loading-state surface"><div class="spinner"></div></div><template v-else>
        <div class="summary-grid"><div class="summary-card surface"><span class="summary-label">소속 그룹</span><strong class="summary-value">{{ groups.length }}</strong></div><div class="summary-card surface"><span class="summary-label">진행 중 요청</span><strong class="summary-value">{{ openCount }}</strong></div><div class="summary-card surface"><span class="summary-label">완료한 요청</span><strong class="summary-value">{{ completedCount }}</strong></div></div>
        <div class="quick-grid"><router-link to="/groups" class="quick-card surface"><span>⌂</span><div><strong>그룹 선택</strong><p>소속 워크스페이스를 확인합니다.</p></div><i>→</i></router-link><router-link v-if="currentId" :to="`/groups/${currentId}/assets`" class="quick-card surface"><span>⌕</span><div><strong>자산 찾기</strong><p>현재 그룹에서 대여할 자산을 찾습니다.</p></div><i>→</i></router-link><router-link v-if="currentId" :to="`/groups/${currentId}/loans`" class="quick-card surface"><span>↔</span><div><strong>내 요청</strong><p>대여·반납·도입 상태를 봅니다.</p></div><i>→</i></router-link></div>
        <section class="groups surface"><div class="section-head"><h3>내 그룹</h3><router-link to="/groups">그룹 관리 →</router-link></div><div class="group-list"><router-link v-for="group in groups" :key="group.id" :to="`/groups/${group.id}`"><span>{{ group.name.charAt(0) }}</span><div><strong>{{ group.name }}</strong><small>{{ group.currentRole==='MANAGER'?'그룹 관리자':'구성원' }}</small></div></router-link><p v-if="!groups.length">참여 중인 그룹이 없습니다.</p></div></section>
        <section class="principle surface"><span>AGILE + MSA + ML</span><div><h3>도메인 흐름은 명확하게, AI는 검증 가능한 관리자 판단에</h3><p>그룹별 대여 운영과 시간순 모델 평가를 분리해 설계 의도와 학습 효과를 함께 보여줍니다.</p></div></section>
      </template>
    </section>
  </div></main></div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import AppHeader from '@/components/AppHeader.vue'
import { enrollmentApi } from '@/api/enrollment.js'
import { useAuthStore } from '@/store/auth.js'
import { useGroupStore } from '@/store/group.js'
const auth=useAuthStore(),groupStore=useGroupStore(),requests=ref([]),loading=ref(true),groups=computed(()=>groupStore.groups),currentId=computed(()=>groupStore.currentGroup?.id||Number(sessionStorage.getItem('current_group_id'))||null)
const openCount=computed(()=>requests.value.filter(item=>['PENDING','GROUP_APPROVED','ACTIVE','RETURN_REQUESTED','BUDGET_APPROVED'].includes(item.status)).length),completedCount=computed(()=>requests.value.filter(item=>['RETURNED','RECEIVED'].includes(item.status)).length)
onMounted(async()=>{try{await groupStore.fetchGroups();const res=await enrollmentApi.getMyEnrollments();requests.value=res.data?.data??[]}finally{loading.value=false}})
</script>

<style scoped>
.profile-layout{display:grid;grid-template-columns:270px 1fr;gap:24px;align-items:start}.profile-card{position:sticky;top:90px;padding:27px;text-align:center}.large-avatar{width:70px;height:70px;margin:0 auto 13px;display:grid;place-items:center;color:#fff;background:var(--color-navy);border-radius:22px 22px 8px 22px;font-size:25px;font-weight:800}.role-badge{display:inline-block;padding:4px 8px;color:var(--color-primary);background:var(--color-primary-light);border-radius:999px;font-size:9px;font-weight:800}.profile-card h2{margin-top:10px;color:var(--color-navy);font-size:19px}.profile-card>p{margin-top:3px;color:var(--color-text-muted);font-size:10px;word-break:break-all}.profile-divider{margin:21px 0;border-top:1px solid var(--color-border)}.profile-card small{color:var(--color-text-muted);font-size:9px;line-height:1.7}.compact-heading{margin-bottom:22px}.quick-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.quick-card{display:grid;grid-template-columns:40px 1fr auto;align-items:center;gap:11px;padding:17px;transition:var(--transition)}.quick-card:hover{transform:translateY(-2px);box-shadow:var(--shadow-md)}.quick-card>span{width:39px;height:39px;display:grid;place-items:center;color:var(--color-primary);background:var(--color-primary-light);border-radius:11px}.quick-card div{display:flex;flex-direction:column}.quick-card strong{font-size:11px}.quick-card p{color:var(--color-text-muted);font-size:8px}.quick-card i{color:var(--color-text-muted);font-style:normal}.groups{margin-top:17px;padding:20px}.section-head{display:flex;justify-content:space-between}.section-head h3{font-size:13px}.section-head a{color:var(--color-primary);font-size:9px;font-weight:700}.group-list{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:13px}.group-list>a{display:flex;align-items:center;gap:9px;padding:10px;background:var(--color-bg-secondary);border-radius:9px}.group-list>a>span{width:31px;height:31px;display:grid;place-items:center;color:#fff;background:var(--color-primary);border-radius:8px;font-size:10px;font-weight:800}.group-list div{display:flex;flex-direction:column}.group-list strong{font-size:10px}.group-list small,.group-list p{color:var(--color-text-muted);font-size:8px}.principle{display:grid;grid-template-columns:120px 1fr;gap:20px;margin-top:17px;padding:22px;background:linear-gradient(120deg,#102a43,#14493f);color:#fff}.principle>span{color:#72dbc0;font-size:8px;font-weight:800;letter-spacing:.1em}.principle h3{font-size:13px}.principle p{margin-top:4px;color:#b9c8d0;font-size:9px}@media(max-width:850px){.profile-layout{grid-template-columns:1fr}.profile-card{position:static}}@media(max-width:650px){.quick-grid,.group-list{grid-template-columns:1fr}.principle{grid-template-columns:1fr}}
</style>
